
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zackBlogs?useUnicode=true&characterEncoding=utf-8
    username: 666666
    password: 666666


mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: cn.rmonkey.entity
server:
  port: 8888
